language: php

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer selfupdate
  - composer install -n

script:
  - bin/phpspec
